appliances_store/appliances_store/urls.py
from xml.etree.ElementInclude import include
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('info.urls')),
    path('admin/', admin.site.urls),
] \
                + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
                + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

appliances_store/info/urls.py
from atexit import register
from unicodedata import name
from django.urls import path, include, re_path
from .views import *
from . import views



urlpatterns = [
    path('', home),
    path('accounts/', include('allauth.urls')),
    re_path(r'^product/(?P<product_id>\w+)/$', views.product, name='product'),
    re_path(r'^basket_adding/$', views.basket_adding, name='basket_adding'),
    re_path(r'^checkout/$', views.checkout, name='checkout'),
    path('category/', views.category, name= 'category'),
    path('for-kitchen/', views.for_kitchen, name='for-kitchen'),
    path('dishes', views.dishes, name='dishes'),
    path('tec-for-home', views.tec_for_home, name='tec-for-home'),
    path('health-and-beauty', views.health_and_beauty, name='health-and-beauty'),
    path('instruments', views.instruments, name="instruments"),
    path('other', views.other, name="other"),
    path('delivery', views.delivery, name="delivery"),
    path('payment', views.payment, name="payment"),
    path('graph-work', views.grap_work, name="graph-work"),
    path('refrigerators', views.refrigerators, name="refrigerators"),
    path('plates', views.plates, name="plates"),
    path('microwave', views.microwave, name="microwave"),
    path('teapot', views.teapot, name="teapot"),
    path('coffeMachine', views.coffeMachine, name="coffeMachine"),
    path('pans', views.pans, name="pans"),
    path('pots', views.pots, name="pots"),
    path('serving', views.serving, name="serving"),
    path('kitchenware', views.kitchenware, name="kitchenware"),
    path('vacuum', views.vacuum, name="vacuum"),
    path('washing_machines', views.washing_machines, name="washing_machines"),
    path('irons', views.irons, name="irons"),
    path('telephones', views.telephones, name="telephones"),
    path('scales', views.scales, name="scales"),
    path('electric_shaver', views.electric_shaver, name="electric_shaver"),
    path('hairdryers', views.hairdryers, name="hairdryers"),
    path('trimmers', views.trimmers, name="trimmers"),
]

appliances_store/info/models.py
import email
from unicodedata import name
from django.db import models
from django.urls import reverse

class Status(models.Model):
    name = models.CharField(max_length=24, blank=True, null=True, default=None)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return "Статус %s" % self.name

    class Meta:
        verbose_name = 'Статус заказа'
        verbose_name_plural = 'Статусы заказа'

class ProductCategory(models.Model):
    name = models.CharField(max_length=64, blank=True, null=True, default=None)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return "%s" % self.name

    class Meta:
        verbose_name = 'Категория товара'
        verbose_name_plural = 'Категория товаров'

class Order(models.Model):

    total_price = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    customer_name = models.CharField(max_length=64, blank=True, null=True, default=None)
    customer_email = models.EmailField(blank=True, null=True, default=None)
    customer_phone = models.CharField(max_length=48, blank=True, null=True, default=None)
    customer_address = models.CharField(max_length=128, blank=True, null=True, default=None)
    comments = models.TextField(blank=True, null=True, default=None)
    status = models.ForeignKey(Status, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return "Заказ %s %s" % (self.id, self.status.name)

    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

    def save(self, *args, **kwargs):

        super(Order, self).save(*args, **kwargs)



class Product(models.Model):
    name = models.CharField(max_length=64, blank=True, null=True, default=None)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    discount = models.IntegerField(default=0)
    category = models.ForeignKey(ProductCategory, blank=True, null=True, default=None, on_delete=models.CASCADE)
    short_description = models.TextField(blank=True, null=True, default=None)
    description = models.TextField(blank=True, null=True, default=None)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return "%s, %s" % (self.price, self.name)

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'

class ProductInOrder(models.Model):
    order = models.ForeignKey(Order, blank=True, null=True, default=None, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, blank=True, null=True, default=None, on_delete=models.CASCADE)
    nmb = models.IntegerField(default=1)
    price_per_item = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    total_price = models.DecimalField(max_digits=10, decimal_places=2, default=0)#price*nmb
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return "%s" % self.product.name

    class Meta:
        verbose_name = 'Товар в заказе'
        verbose_name_plural = 'Товары в заказе'


    def save(self, *args, **kwargs):
        price_per_item = self.product.price
        self.price_per_item = price_per_item
        print (self.nmb)

        self.total_price = int(self.nmb) * price_per_item

        super(ProductInOrder, self).save(*args, **kwargs)


class ProductImage(models.Model):
    product = models.ForeignKey(Product, blank=True, null=True, default=None, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='products_images/')
    is_main = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return "%s" % self.id

    class Meta:
        verbose_name = 'Фотография'
        verbose_name_plural = 'Фотографии'

class ProductInBasket(models.Model):
    session_key = models.CharField(max_length=128, blank=True, null=True, default=None)
    order = models.ForeignKey(Order, blank=True, null=True, default=None, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, blank=True, null=True, default=None, on_delete=models.CASCADE)
    nmb = models.IntegerField(default=1)
    price_per_item = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    total_price = models.DecimalField(max_digits=10, decimal_places=2, default=0)#price*nmb
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return "%s" % self.product.name

    class Meta:
        verbose_name = 'Товар в корзине'
        verbose_name_plural = 'Товары в корзине'

    def save(self, *args, **kwargs):
        price_per_item = self.product.price
        self.price_per_item = price_per_item
        print (self.nmb)

        self.total_price = int(self.nmb) * price_per_item

        super(ProductInBasket, self).save(*args, **kwargs)

appliances_store/info/views.py
from datetime import date
from email import header
from math import prod
from re import template
from threading import local
from urllib import request
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from django.contrib.auth import authenticate, login
from .models import *


def home(request):
    products_images = ProductImage.objects.filter(product__category__id=1)
    products_images2 = ProductImage.objects.filter(product__category__id=2)
    # products_images_plates = products_images.filter(product__category__id=1)
    return render(request, 'info/index.html', locals())

def category(request):
    return render(request, 'products/category.html', locals())

def for_kitchen(request):
    return render(request, 'category/for-kitchen.html', locals())

def dishes(request):
    return render(request, 'category/dishes.html', locals())

def tec_for_home(request):
    return render(request, 'category/tec-for-home.html', locals())

def health_and_beauty(request):
    return render(request, 'category/health-and-beauty.html', locals())

def instruments(request):
    return render(request, 'category/instruments.html', locals())

def other(request):
    return render(request, 'category/other.html', locals())

def delivery(request):
    return render(request, 'info/delivery.html', locals())

def payment(request):
    return render(request, 'info/payment.html', locals())

def grap_work(request):
    return render(request, 'info/grap-work.html', locals())

def product(request, product_id):
    product = Product.objects.get(id=product_id)

    session_key = request.session.session_key
    if not session_key:
        request.session.cycle_key()
    print(request.session.session_key)

    return render(request, 'products/product.html', locals())


def basket_adding(request):
    
    return_dict = dict()
    session_key = request.session.session_key
    print (request.POST)
    data = request.POST
    product_id = data.get("product_id")
    nmb = data.get("nmb")
    is_delete = data.get("is_delete")

    if is_delete == 'true':
        ProductInBasket.objects.filter(id=product_id).update(is_active=False)
    else:
        new_product, created = ProductInBasket.objects.get_or_create(session_key=session_key, product_id=product_id,
                                                                     is_active=True, defaults={"nmb": nmb})
        if not created:
            print ("not created")
            new_product.nmb += int(nmb)
            new_product.save(force_update=True)

    #common code for 2 cases
    products_in_basket = ProductInBasket.objects.filter(session_key=session_key, is_active=True, order__isnull=True)
    products_total_nmb = products_in_basket.count()
    
    return_dict["products_total_nmb"] = products_total_nmb

    return_dict["products"] = list()

    for item in  products_in_basket:
        product_dict = dict()
        product_dict["id"] = item.id
        product_dict["name"] = item.product.name
        product_dict["price_per_item"] = item.price_per_item
        product_dict["nmb"] = item.nmb
        return_dict["products"].append(product_dict)

    return JsonResponse(return_dict)

def checkout(request):
    session_key = request.session.session_key
    products_in_basket = ProductInBasket.objects.filter(session_key=session_key, is_active=True)
    return render(request, 'products/checkout.html', locals())

def refrigerators(request):
    products_images_refrigerators = ProductImage.objects.filter(product__category__id=3)
    return render(request, 'subcategory/tec-for-kitchen/refrigerators.html', locals())

def plates(request):
    products_images_plates = ProductImage.objects.filter(product__category__id=4)
    return render(request, 'subcategory/tec-for-kitchen/plates.html', locals())

def microwave(request):
    products_images_microwave = ProductImage.objects.filter(product__category__id=5)
    return render(request, 'subcategory/tec-for-kitchen/microwave.html', locals())

def teapot(request):
    products_images_teapot = ProductImage.objects.filter(product__category__id=6)
    return render(request, 'subcategory/tec-for-kitchen/teapot.html', locals())

def coffeMachine(request):
    products_images_coffeMachine = ProductImage.objects.filter(product__category__id=7)
    return render(request, 'subcategory/tec-for-kitchen/coffeMachine.html', locals())

def pans(request):
    products_images_pans = ProductImage.objects.filter(product__category__id=8)
    return render(request, 'subcategory/dishes/pans.html', locals())

def pots(request):
    products_images_pots = ProductImage.objects.filter(product__category__id=9)
    return render(request, 'subcategory/dishes/pots.html', locals())

def serving(request):
    products_images_serving = ProductImage.objects.filter(product__category__id=10)
    return render(request, 'subcategory/dishes/serving.html', locals())

def kitchenware(request):
    products_images_kitchenware = ProductImage.objects.filter(product__category__id=11)
    return render(request, 'subcategory/dishes/kitchenware.html', locals())

def vacuum(request):
    products_images_vacuum = ProductImage.objects.filter(product__category__id=12)
    return render(request, 'subcategory/tec-for-home/vacuum.html', locals())

def washing_machines(request):
    products_images_washing_machines = ProductImage.objects.filter(product__category__id=13)
    return render(request, 'subcategory/tec-for-home/washing_machines.html', locals())

def irons(request):
    products_images_irons = ProductImage.objects.filter(product__category__id=14)
    return render(request, 'subcategory/tec-for-home/irons.html', locals())

def telephones(request):
    products_images_telephones = ProductImage.objects.filter(product__category__id=15)
    return render(request, 'subcategory/tec-for-home/telephones.html', locals())

def scales(request):
    products_images_scales = ProductImage.objects.filter(product__category__id=16)
    return render(request, 'subcategory/h&b/scales.html', locals())

def electric_shaver(request):
    products_images_electric_shaver = ProductImage.objects.filter(product__category__id=17)
    return render(request, 'subcategory/h&b/electric_shaver.html', locals())

def hairdryers(request):
    products_images_hairdryers = ProductImage.objects.filter(product__category__id=18)
    return render(request, 'subcategory/h&b/hairdryers.html', locals())

def trimmers(request):
    products_images_trimmers = ProductImage.objects.filter(product__category__id=19)
    return render(request, 'subcategory/h&b/trimmers.html', locals())

appliances_store/info/templates/products/category.html
{% extends "account/base.html" %}
{% load static %}


{% block content%}
<style>
    body {
        background-color: white;
    }
</style>

<div class="container py-2">
    <div class="container px-4 px-lg-5 my-5 ms-5">
        <nav class="navbar navbar-expand-lg navbar-light">
            <div class="btn-group" style="width: 200px;">
                <a href="{% url 'category' %}"><button type="button" class="btn btn-success" style="font-weight: 600;"
                        aria-expanded="false">Все
                        категории</button></a>
                <button type="button" class="btn btn-success dropdown-toggle dropdown-toggle-split"
                    data-bs-toggle="dropdown" aria-expanded="false">
                    <span class="visually-hidden">Toggle Dropdown</span>
                </button>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item mt-2" href="{% url 'for-kitchen' %}">Товары для кухни</a></li>
                    <li><a class="dropdown-item mt-2" href="{% url 'dishes' %}">Посуда</a></li>
                    <li><a class="dropdown-item mt-2" href="{% url 'tec-for-home' %}">Техника для дома</a></li>
                    <li><a class="dropdown-item mt-2" href="{% url 'health-and-beauty' %}">Красота и здоровье</a></li>
                    <li><a class="dropdown-item mt-2" href="{% url 'instruments' %}">Инструменты</a></li>
                    <li><a class="dropdown-item mt-2" href="{% url 'other' %}">Прочее</a></li>
                </ul>
            </div>
            <div class="container-fluid">

                <div class="collapse navbar-collapse ms-4" id="navbarNavAltMarkup">
                    <div class="navbar-nav">
                        <a class="delivery me-3" href="{% url 'delivery' %}"> Доставка </a>
                        <a class="payment me-3" href="{% url 'payment' %}">Оплата</a>
                        <a class="graph-work me-3" href="{% url 'graph-work' %}">График работы</a>
                        <a class="hits me-3" href="/#hits">Хиты продаж</a>
                    </div>
                </div>
            </div>
        </nav>
    </div>
    <div class="row justify-content-md-center">
        <div class="col-md-auto ms-4">
            <a href="{% url 'for-kitchen' %}">
                <div class="card" style="width: 14rem; border: 2px solid #f7f7f7;">
                    <img src="{% static 'img\for-kitchen\tekhn-dlya-kukh.jpg' %}" class="card-img-top" alt="..."
                        width="150" height="120">
                    <div class="card-body">
                        <h5 class="card-title text-center">Товары для кухни</h5>
                    </div>
                </div>
            </a>
        </div>
        <div class="col-md-auto ms-4">
            <a href="{% url 'dishes' %}">
                <div class="card" style="width: 14rem; border: 2px solid #f7f7f7;">
                    <img src="{% static 'img\dishes\Posuda.jpg' %}" class="card-img-top" alt="..." width="150"
                        height="120">
                    <div class="card-body">
                        <h5 class="card-title text-center">Посуда</h5>
                    </div>
                </div>
            </a>
        </div>
        <div class="col-md-auto ms-4">
            <a href="{% url 'tec-for-home' %}">
                <div class="card" style="width: 14rem; border: 2px solid #f7f7f7;">
                    <img src="{% static 'img\tec-for-home\tekh-dlya-doma.jpg' %}" class="card-img-top" alt="..."
                        width="150" height="120">
                    <div class="card-body">
                        <h5 class="card-title text-center">Техника для дома</h5>
                    </div>
                </div>
            </a>
        </div>
    </div>

    <div class="row justify-content-md-center py-5">
        <div class="col-md-auto ms-4">
            <a href="{% url 'health-and-beauty' %}">
                <div class="card" style="width: 14rem; border: 2px solid #f7f7f7;">
                    <img src="{% static 'img\healt&beauty\krasota-i.jpg' %}" class="card-img-top" alt="..." width="150"
                        height="120">
                    <div class="card-body">
                        <h5 class="card-title text-center">Красота и здоровье</h5>
                    </div>
                </div>
            </a>
        </div>
        <div class="col-md-auto ms-4">
            <a href="{% url 'instruments' %}">
                <div class="card" style="width: 14rem; border: 2px solid #f7f7f7;">
                    <img src="{% static 'img\instruments\Instrumenty.jpg' %}" class="card-img-top" alt="..." width="150"
                        height="120">
                    <div class="card-body">
                        <h5 class="card-title text-center">Инструменты</h5>
                    </div>
                </div>
            </a>
        </div>
        <div class="col-md-auto ms-4">
            <a href="{% url 'other' %}">
                <div class="card" style="width: 14rem; border: 2px solid #f7f7f7;">
                    <img src="{% static 'img\other\prochee.jpg' %}" class="card-img-top" alt="..." width="150"
                        height="120">
                    <div class="card-body">
                        <h5 class="card-title text-center">Прочее</h5>
                    </div>
                </div>
            </a>
        </div>
    </div>

</div>

{% endblock %}

appliances_store/info/templates/products/product.html
{% extends "account/base.html" %}
{% load static %}
<!DOCTYPE html>
<html>

<head>

    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>{{ product.name }}</title>
        <!-- Bootstrap-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
            integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
            crossorigin="anonymous"></script>
        <!-- Core theme CSS (includes Bootstrap)-->
        {% load static %}
        <link rel="stylesheet" href="{% static 'styles/main.css' %}">
    </head>
</head>

<body>
    {% block content%}
    <div class="container mt-5 mb-5">
        <div class="container px-4 px-lg-5 my-5 ms-5">
            <nav class="navbar navbar-expand-lg navbar-light">
                <div class="btn-group" style="width: 200px;">
                    <a href="{% url 'category' %}"><button type="button" class="btn btn-success"
                            style="font-weight: 600;" aria-expanded="false">Все
                            категории</button></a>
                    <button type="button" class="btn btn-success dropdown-toggle dropdown-toggle-split"
                        data-bs-toggle="dropdown" aria-expanded="false">
                        <span class="visually-hidden">Toggle Dropdown</span>
                    </button>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item mt-2" href="{% url 'for-kitchen' %}">Товары для кухни</a></li>
                        <li><a class="dropdown-item mt-2" href="{% url 'dishes' %}">Посуда</a></li>
                        <li><a class="dropdown-item mt-2" href="{% url 'tec-for-home' %}">Техника для дома</a></li>
                        <li><a class="dropdown-item mt-2" href="{% url 'health-and-beauty' %}">Красота и здоровье</a>
                        </li>
                        <li><a class="dropdown-item mt-2" href="{% url 'instruments' %}">Инструменты</a></li>
                        <li><a class="dropdown-item mt-2" href="{% url 'other' %}">Прочее</a></li>
                    </ul>
                </div>
                <div class="container-fluid">

                    <div class="collapse navbar-collapse ms-4" id="navbarNavAltMarkup">
                        <div class="navbar-nav">
                            <a class="delivery me-3" href="{% url 'delivery' %}"> Доставка </a>
                            <a class="payment me-3" href="{% url 'payment' %}">Оплата</a>
                            <a class="graph-work me-3" href="{% url 'graph-work' %}">График работы</a>
                            <a class="hits me-3" href="/#hits">Хиты продаж</a>
                        </div>
                    </div>
                </div>
            </nav>
        </div>
        <div class="row d-flex justify-content-center">
            <div class="col-lg-10">
                <div class="card">
                    <div class="row">
                        <div class="col-md-6">
                            {% for image_item in product.productimage_set.all %}
                            <div class="images p-3">
                                <div class="text-center p-4"> <img id="main-image" src="{{ image_item.image.url }}"
                                        width="250" /> </div>

                            </div>
                            {% endfor %}
                        </div>
                        <div class="col-md-6">
                            <div class="product p-4">
                                <div class="d-flex justify-content-between align-items-center">
                                </div>
                                <div class="mt-4 mb-3">
                                    <h3 class="text-uppercase" style="color: #198754;">{{ product.name }}</h3>
                                    <div class="price d-flex flex-row align-items-center"> <span class="act-price">
                                            <h4 class="">Цена:
                                                {{ product.price }} ₸ </h4>
                                        </span>
                                    </div>
                                </div>
                                <p class="about">{{ product.description }}
                                </p>

                                <div class="d-flex flex-row py-5 mt-5">
                                    <form id="form_buying_product" action="{% url 'basket_adding' %}">{% csrf_token %}
                                        <div class="d-flex">
                                            <input type="number" class="form-control h-25" name="number" id="number"
                                                placeholder="Количество...">

                                            <button type="submit" id="submit_btn"
                                                class="btn btn-success btn-buy ms-3 form-control w-50"
                                                data-product_id="{{ product.id }}" data-name="{{ product.name }}"
                                                data-price="{{ product.price }}">
                                                В КОРЗИНУ
                                            </button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="space">

    </div>
    {% endblock %}
    <script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>

    <script src="{% static 'js/scripts.js' %}"></script>
</body>

</html>